"""Constants for the Duet3D integration."""
from homeassistant.const import (
    UnitOfTemperature,
)

DOMAIN = "duet3d"

DEFAULT_NAME = "Duet3D"
CONF_NAME = "name"
CONF_STANDALONE = "standalone"
ATTR_GCODE = "gcode"
CONF_SBC_API = "/machine"
CONF_SBC_STATUS_PATH = "/status"
CONF_SBC_GCODE_PATH = "/code"
CONF_JSON_HEADER = {"Accept": "application/json"}
CONF_TEXT_PLAIN_HEADER = {"Content-Type": "text/plain"}
CONF_STANDALONE_API = "/rr_model"
CONF_STANDALONE_GCODE_PATH = "/rr_gcode"
CONF_BASE_URL = "base_url"
SERVICE_SEND_GCODE = "send_code"
SERVICE_HOME = "home"
SERVICE_PAUSE = "pause"
SERVICE_RESUME = "resume"
SERVICE_CANCEL = "cancel"
SERVICE_ACKNOWLEDGE_MESSAGE = "acknowledge_message"
SERVICE_EMERGENCY_STOP = "emergency_stop"
SERVICE_RESET_AFTER_EMERGENCY_STOP = "reset_after_emergency_stop"
SERVICE_LOAD_FILAMENT = "load_filament"
SERVICE_UNLOAD_FILAMENT = "unload_filament"
SERVICE_CANCEL_OBJECT = "cancel_object"
ATTR_OBJECT = "object"
ATTR_AXES = "axes"
ATTR_TOOL = "tool"
ATTR_FILAMENT = "filament"
ATTR_CANCEL = "cancel"
CONF_INTERVAL = "update_interval"
CONF_PRINTING_INTERVAL = "printing_interval"
CONF_WEBCAM_URL = "webcam_url"
# Seconds between polls while a job is running. A Duet Wi-Fi module is far weaker than
# a Raspberry Pi, and a whole standalone poll is 7 requests, so this is not lower.
DEFAULT_PRINTING_INTERVAL = 5
# Event fired on the Home Assistant bus for job lifecycle changes (see events.py).
EVENT_NAME = "duet3d_event"

# Standalone mode polls these top-level object model keys, each as one request
# (key=<name>&flags=d99vn: d99 = full depth, v = verbose fields, n = include nulls).
# Their results are assembled under ``status`` so that every json_path below works
# the same in standalone mode and against the DSF /machine/status document (SBC).
# Add a key here before reading anything under it.
STANDALONE_POLL_KEYS = (
    "state",
    "job",
    "heat",
    "tools",
    "move",
    "fans",
    "sensors.filamentMonitors",  # runout needs to be prompt, but the rest of ``sensors`` is large
)
# Things that rarely change (and cost a request each) are refreshed this often
# instead of on every poll. SBC mode gets everything in its one request anyway.
STANDALONE_SLOW_POLL_KEYS = ("boards", "network", "volumes", "ledStrips")
STANDALONE_SLOW_POLL_SECONDS = 60
STANDALONE_POLL_FLAGS = "d99vn"
MACRO_DIRECTORY = "0:/macros"
FILAMENT_DIRECTORY = "0:/filaments"
FIRMWARE_RELEASES_URL = "https://api.github.com/repos/Duet3D/RepRapFirmware/releases/latest"
# Polls that may fail in a row before entities go unavailable (the last data is kept).
TOLERATED_FAILED_POLLS = 2

# Matches legacy temperature sensors, whose unique_id was "<tool number>-<type>-<entry id>"
# and which read heaters[<tool number>] regardless of which heater the tool uses.
LEGACY_TEMPERATURE_UNIQUE_ID = r"\d+-(current|active|standby)-"

SENSOR_TYPES = {
    "Heat": {"json_path": "status.heat"},
    "Current State": {
        "json_path": "status.state.status",
        "unit": None,
        "icon": "mdi:printer-3d",
    },
    "Time Remaining": {
        "json_path": "status.job.timesLeft.file",
        "unit": "min",
        "icon": "mdi:clock-end",
    },
    "Slicer Time Remaining": {
        "json_path": "status.job.timesLeft.slicer",
        "unit": "min",
        "icon": "mdi:clock-end",
    },
    "Time Elapsed": {
        "json_path": "status.job.duration",
        "unit": "min",
        "icon": "mdi:clock-start",
    },
    "Progress": {
        "json_path": "status.job.file.filament",
        "unit": "%",
        "icon": "mdi:clock-end",
    },
    "Filament Extrusion": {
        "json_path": "status.job.rawExtrusion",
        "unit": "mm",
        "icon": "mdi:printer-3d-nozzle",
    },
    "Filament Time Remaining": {"json_path": "status.job.timesLeft.filament"},
    "Warm-up Duration": {"json_path": "status.job.warmUpDuration"},
    "Last File Name": {"json_path": "status.job.lastFileName"},
    "Layer Height": {"json_path": "status.job.file.layerHeight"},
    "Object Height": {"json_path": "status.job.file.height"},
    "Generated By": {"json_path": "status.job.file.generatedBy"},
    "Speed Factor": {"json_path": "status.move.speedFactor"},
    "Display Message": {"json_path": "status.state.displayMessage"},
    "Machine State": {"json_path": "status.state"},
    "Axes": {"json_path": "status.move.axes"},
    "Extruders": {"json_path": "status.move.extruders"},
    "Tools": {"json_path": "status.tools"},
    "Current Tool": {"json_path": "status.state.currentTool"},
    "Position": {
        "json_path": "status.move.axes",
        "axes": ["X", "Y", "Z"],
        "unit": "mm,mm,mm",
        "icon": "mdi:axis-x-arrow",
    },
    "Thumbnail": {"json_path": "status.job.file.thumbnails", "icon": "mdi:picture"},
    "Print Speed": {"json_path": "status.move.currentMove.requestedSpeed"},
    "Build": {"json_path": "status.job.build"},
    "Current Layer": {"json_path": "status.job.layer"},
    "Total Layers": {"json_path": "status.job.file.numLayers"},
    "File Name": {"json_path": "status.job.file.fileName"},
}

# ``state.status`` values in which a job is under way, so the printer is polled faster.
PRINTING_STATES = {"processing", "pausing", "resuming", "cancelling", "changingTool"}

PRINTER_STATUS = {
    "starting",
    "simulating",
    "processing",
    "idle",
    "cancelling",
    "busy",
    "disconnected",
    "resuming",
    "halted",
    "changingTool",
    "off",
    "paused",
    "pausing",
    "updating",
}
